name: Publish to PyPI
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read
jobs:
  build-and-publish:
    environment: pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -U build
      - run: python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          verbose: true
